/*
 * @Author: your name
 * @Date: 2021-11-16 17:56:55
 * @LastEditTime: 2021-12-09 17:49:54
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: \Projects\NeteaseCloudMusic\Vue-NeteaseCloudMusic\src\store\mutationsTypes.js
 */

// 自动登录
const UPDATE_AUTO_LOGIN = "UPDATE_AUTO_LOGIN";

// 登录窗口显示
const UPDATE_LOGIN_WINDOW_SHOW = "UPDATE_LOGIN_WINDOW_SHOW";

// 登录窗口移动
const UPDATE_LOGIN_WINDOW_MOVE = "UPDATE_LOGIN_WINDOW_MOVE";

// 登录方式
const UPDATE_LOGIN_MODE = "UPDATE_LOGIN_MODE";

// 登录是否同意政策
const UPDATE_LOGIN_POLICY = "UPDATE_LOGIN_POLICY";

// 登录政策提示显示
const UPDATE_LOGIN_POLICY_TIP_SHOW = "UPDATE_LOGIN_POLICY_TIP_SHOW";

// 登录验证码发送提示
const UPDATE_LOGIN_CAPTCHA_TIP_SHOW = "UPDATE_LOGIN_CAPTCHA_TIP_SHOW";

// 登录发送验证码数量
const INCREASE_LOGIN_CAPTCHA_COUNT = "INCREASE_LOGIN_CAPTCHA_COUNT";

// 用户登录信息
const UPDATE_USER_LOGIN_INFO = "UPDATE_USER_LOGIN_INFO";

// 登录手机号
const UPDATE_LOGIN_PHONE = "UPDATE_LOGIN_PHONE";

// 登录密码
const UPDATE_LOGIN_PASSWORD = "UPDATE_LOGIN_PASSWORD";

// 用户是否登录
const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";

// 用户账号
const UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";

// 用户详情
const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";

// 用户信息
const UPDATE_USER_SUBCOUNT = "UPDATE_USER_SUBCOUNT";

// 用户私信
const UPDATE_USER_MSG_PRIVATE = "UPDATE_USER_MSG_PRIVATE";

// 音频播放器
const INIT_PLAYER_AUDIO = "INIT_PLAYER_AUDIO";

// 音频播放器配置
const UPDATE_PLAYER_AUDIO_CONFIG = "UPDATE_PLAYER_AUDIO_CONFIG";

// 当前音乐播放时间
const UPDATE_AUDIO_CURRENT_TIME = "UPDATE_AUDIO_CURRENT_TIME";

// 音乐播放Interval
const UPDATE_AUDIO_INTERVAL = "UPDATE_AUDIO_INTERVAL";

// 增加歌曲信息
const ADD_PLAYLIST_SONGS_INFO = "ADD_PLAYLIST_SONGS_INFO";

//删除歌曲信息
const DELETE_PLAYLIST_SONGS_INFO = "DELETE_PLAYLIST_SONGS_INFO";


export {
  UPDATE_AUTO_LOGIN,
  UPDATE_LOGIN_WINDOW_SHOW,
  UPDATE_LOGIN_WINDOW_MOVE,
  UPDATE_LOGIN_MODE,
  UPDATE_LOGIN_POLICY,
  UPDATE_LOGIN_POLICY_TIP_SHOW,
  UPDATE_LOGIN_CAPTCHA_TIP_SHOW,
  INCREASE_LOGIN_CAPTCHA_COUNT,
  UPDATE_USER_LOGIN_INFO,
  UPDATE_LOGIN_PHONE,
  UPDATE_LOGIN_PASSWORD,
  UPDATE_USER_LOGIN,
  UPDATE_USER_ACCOUNT,
  UPDATE_USER_DETAIL,
  UPDATE_USER_SUBCOUNT,
  UPDATE_USER_MSG_PRIVATE,
  ADD_PLAYLIST_SONGS_INFO,
  DELETE_PLAYLIST_SONGS_INFO,
  INIT_PLAYER_AUDIO,
  UPDATE_PLAYER_AUDIO_CONFIG,
  UPDATE_AUDIO_CURRENT_TIME,
  UPDATE_AUDIO_INTERVAL
};
